name: waveflutterapp
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # image_picker: ^1.0.7
  qr_flutter: ^4.1.0
  # mobile_scanner: ^3.5.7
  http: ^0.13.4
  shared_preferences: ^2.2.2
  # flutter_contact: ^0.9.1+8
  flutter_contacts: ^1.1.7+1
  permission_handler: ^10.2.0
  dio: ^5.0.0 # Utilisez la dernière version compatible avec votre projet
  otp_text_field: ^1.1.3
  path: ^1.9.0
  path_provider: ^2.0.15
  image_picker: ^1.1.2
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  flutter_svg: ^2.0.7
  mobile_scanner: ^6.0.2
  just_audio: ^0.9.36
  provider: ^6.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

# Configuration pour flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/elzo.jpeg"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/elzo.jpeg"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/elzo.jpeg
    - assets/images/qr_code.png
    - assets/sounds/beep.mp3
